version: "3.8"
# variours containers we use during developement 
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      # "host-machine port: port inside the container"
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  account:
    build:
      # context -> to look in the account folder 
      # target -> target of the multi-stage build 
      context: ./account
      target: builder
    image: account
    env_file: .env.dev
    expose:
      - "8080"
    # labels tell traefik to look for this container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`niruthi.test`) && PathPrefix(`/api/account`)"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
    # have to use $$ (double-dollar) so docker doesn't try to substitute a variable
    command: reflex -r "\.go$$" -s -- sh -c "go run ."
